#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged || (
  echo '❌ ❌ ❌ Lint Stage Failed. ❌ ❌ ❌
        Please make the changes required above.'
  false;
)

# Check tsconfig standards
yarn check-types || (
  echo '❌ ❌ ❌ Failed Type check. ❌ ❌ ❌
        Please make the changes required above.'
  false;
)

# Check Prettier standards
yarn check-format || (
  echo '🤢 🤮 🤢 🤮 Your code style is disgusting. 🤮 🤢 🤮 🤢 
        Prettier check failed. Please run "yarn format", add changes and try again.'
  false;
)

# Check Eslint standards
yarn check-lint || (
  echo '😤 🤌 😤 🤌 Your linting check failed!! 😤 🤌 😤 🤌 
        ESLint check failed. Please fix all of it, add changes and try again.'
  false;
)

# If everything passes... Now we can now execute a push
echo '✅✅✅✅ All your checks were successful, you can now push to your remote repo. ✅✅✅✅'