#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# When 'git commit' command is run, an interactive Commitizen
# session to guide us through writing a meaningful commit message.

exec < /dev/tty && git cz --hook || true || (
  echo '❌ ❌ ❌ Failed to execute Commitizen. ❌ ❌ ❌
        Please make the changes required above.'
  false;
)