import Head from 'next/head';
import Link from 'next/link';

import { useStyles } from '@styles/Home';


function Offline() {
  const { classes } = useStyles();

  return (
    <div className={classes.root}>
      <Head>
        <title>Offline | NTS23 by Vladimir De Vico</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <h1>Oops, it looks like you're offline.</h1>
        <p>We're sorry, but it looks like you're not connected to the internet. Please check your connection and try again.</p>
        <Link href="/">
          Go back to the home page
        </Link>
      </main>
      <footer>
        <a
          href="/"
          target="_blank"
          rel="noopener noreferrer"
          style={{
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            minHeight: 48,
            color: 'white',
          }}
          aria-label="Footer powered by link"
        >
          Powered by Vladimir De Vico
        </a>
      </footer>
    </div>
  );
}

export default Offline;
