import { useEffect, useState } from 'react';

import Head from 'next/head';

import ProductCard from '@components/__Common/ProductCard';
import { initializeStore } from '@store/store';
import { useStyles } from '@styles/Home';


function Home() {
  const [products, setProducts] = useState([]);
  const { classes } = useStyles();

  useEffect(() => {
    fetch('http://localhost:5000/api/products')
      .then((res) => {
        return res.json();
      })
      .then((data) => {
        return setProducts(data);
      });
  }, []);

  return (
    <div className={classes.root}>
      <Head>
        <title>Store - App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons/favicon.ico" />
        <link rel="canonical" href="http://localhost:3000/" />
      </Head>
      {products.map((product, index) => {
        return <ProductCard key={index.toString()} name={product.name} price={product.price}/>;
      })}
    </div>
  );
}

export default Home;

/*
 * If you build and start the app, the date returned here will have the same
 * value for all requests, as this method gets executed at build time.
 * You will not see this while in development mode though.
 */
export function getStaticProps() {
  const zustandStore = initializeStore();

  return {
    props: {

      /*
       * The "stringify and then parse again" piece is required as next.js
       * isn't able to serialize it to JSON properly
       */
      initialZustandState: JSON.parse(JSON.stringify(zustandStore.getState())),
    },
  };
}
